name: golang-pipeline
on: push
jobs:
  test:
    runs-on: ubuntu-22.04
    # if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags')
    steps:
      - uses: actions/checkout@v3
      - name: Run Unit Tests
        run: go test